// Naming: ACTION_ENTITY_RESULT
export default {
    SET_FILTERPARAMS: 'SET_FILTERPARAMS',
    SET_TIMESEARCHPARAMS: 'SET_TIMESEARCHPARAMS',
    GET_FOODPOINTS: 'GET_FOODPOINTS',
    CLEAR_DATA_STATE: 'CLEAR_DATA_STATE'
};
